### ISSUE TITLE
Need a way to set the eventual consistency flag

### ISSUE THREAD

**Issue by yanickbelanger** [knarz/datastore-emulator#1]
We wish to disable the eventual consistency in the emulator. It can be achieved by passing the `--consistency=1.0` flag at startup. With this docker image, we can't override the flag. Is it possible to add it to the environment variables, like you did for `DATA_DIR` and `HOST_PORT`? Thank you.

**Comment by knarz** [comment]
Hey, just pushed a commit that makes the init script use the `CONSISTENCY` environment variable. The new build should be done in a couple of minutes.

**Comment by yanickbelanger** [comment]
Awesome, thanks for the quick turnaround!
